title: "Anagram"
meta:
  name: "anagram"
  language: "typescript"
  category: "strings"
  completion_time: "40 minutes"
  review_status: "beta"
content:
  points: 220
  creator: "cuervolu"
  lesson_slug: "la-cocina-de-typescript"
  display_order: 2
  difficulty: "INTERMEDIATE"
  estimated_time: 40
prerequisites:
  required:
    - name: "Hello World"
      slug: "hello-world-typescript"
      reason: "Basic TypeScript syntax and types"
tags:
  concepts:
    - "arrays"
    - "strings"
    - "type guards"
  techniques:
    - "array manipulation"
    - "string comparison"
    - "sorting algorithms"
    - "type narrowing"