title: "Space Age"
meta:
  name: "space_age"
  language: "go"
  category: "types"
  completion_time: "45 minutes"
  review_status: "beta"
content:
  points: 250
  creator: "cuervolu"
  lesson_slug: "go-primeros-pasos"
  display_order: 5
  difficulty: "INTERMEDIATE"
  estimated_time: 45
prerequisites:
  required:
    - name: "Hello World"
      slug: "hello-world-go"
      reason: "Basic Go syntax"
    - name: "Gigasecond"
      slug: "gigasecond-go"
      reason: "Working with types and methods"
tags:
  concepts:
    - "types"
    - "methods"
    - "constants"
  techniques:
    - "custom types"
    - "method receivers"
    - "float calculations"